sudo: false
language: php
php:
  - 5.4
before_script:
- npm install -g gulp surge
- npm install
script:
- gulp build
deploy:
  - surge --project ./dist --domain www.prototypo.io
# deploy:
#   - provider: openshift
#     user: francois.poizat@gmail.com
#     password:
#       secure: bXDxc0af2Uf6Mn7E6KnTtNSKaeotSVITOjlUFAaSCUwQbcK9hkrNoiob4oTHOmijXl8qZV4mWSlHpSFIE//2Lby20+o4xkRMSQUg0dE514ncZYjuLNf5W73k6lT8bSfTlPR63SExv0MiG4LmA3hLtGgissNVoQrNcC1II7QUaWc=
#     app: website
#     domain: prototypo
#     on: master
#   - provider: openshift
#     user: francois.poizat@gmail.com
#     password:
#       secure: bXDxc0af2Uf6Mn7E6KnTtNSKaeotSVITOjlUFAaSCUwQbcK9hkrNoiob4oTHOmijXl8qZV4mWSlHpSFIE//2Lby20+o4xkRMSQUg0dE514ncZYjuLNf5W73k6lT8bSfTlPR63SExv0MiG4LmA3hLtGgissNVoQrNcC1II7QUaWc=
#     app: develop
#     domain: prototypo
#     on: develop
branches:
  only:
    - master
