sudo: false
language: php
php:
  - 5.4
before_script:
- npm install -g gulp surge
- npm install
script:
- gulp build
after_script:
- surge --project ./dist --domain www.prototypo.io
branches:
  only:
    - master
