sudo: false
language: php
php:
  - 7.0
before_script:
- wget -V
- sudo apt-get install wget -y
- nvm install v4.4.4
- npm install -g gulp surge
- npm install
script:
- gulp build
after_script:
- 'curl -L https://github.com/netlify/netlifyctl/releases/download/v0.1.0/netlifyctl-linux-amd64-v0.1.0.tar.gz | tar zx'
- '[ $TRAVIS_BRANCH == "master" -a $TRAVIS_PULL_REQUEST == "false" ] && ./netlifyctl -y -A $NETLIFY_TOKEN deploy'
- '[ $TRAVIS_BRANCH == "develop" -a $TRAVIS_PULL_REQUEST == "false" ] && ./netlifyctl -y -A $NETLIFY_TOKEN -C netlify-dev.toml deploy'
branches:
  only:
    - master
    - develop
