sudo: false
language: php
php:
  - 5.4
before_script:
- nvm install v0.12
- nvm use v0.12
- npm install -g gulp surge
- npm install
script:
- gulp build
after_script:
- '[ "$TRAVIS_BRANCH" == "master" ] && surge --project ./dist --domain www.prototypo.io'
- '[ "$TRAVIS_BRANCH" == "develop" ] && surge --project ./dist --domain devvv.prototypo.io'
branches:
  only:
    - master
    - develop
