sudo: false
language: php
php:
  - 7.0
before_script:
- nvm install v4.4.4
- npm install -g gulp surge
- npm install
script:
- gulp build
after_script:
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then surge --project ./dist --domain www.prototypo.io; fi
- if [ "$TRAVIS_BRANCH" == "develop" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then surge --project ./dist --domain devvv.prototypo.io; fi
branches:
  only:
    - master
    - develop
