language: php
php:
  - 5.4
script: ls
deploy:
  - provider: openshift
    user: francois.poizat@gmail.com
    password:
      secure: BiDezma7feWy9I8XjtGHog6axgtFApJ+bNS7E/EepUoDpHZR6Mk7bGiTSiVRhEm42cinyi7WT2zflGSCyvWUHJ07pcn3zMdPgtOloZCKI5k7SFc4JWZbcuvIFco/EXCd61wshZN5thsCKc/cH/fm4avoJ4OG9RkJ4vQRZJNpLeM=
    app: website
    domain: prototypo
    on: master
  - provider: openshift
    user: francois.poizat@gmail.com
    password:
      secure: BiDezma7feWy9I8XjtGHog6axgtFApJ+bNS7E/EepUoDpHZR6Mk7bGiTSiVRhEm42cinyi7WT2zflGSCyvWUHJ07pcn3zMdPgtOloZCKI5k7SFc4JWZbcuvIFco/EXCd61wshZN5thsCKc/cH/fm4avoJ4OG9RkJ4vQRZJNpLeM=
    app: develop
    domain: prototypo
    on: develop
    deployment_branch: develop
